name: "lighthouse action"
description: "lighthouse action with docker image"
author: "github.com/sijoonlee"

inputs:
  TARGET_ADDRESS:
    description: "http address to examine"
    required: true
    default: "https://ratehub.ca"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"