version: "3.2"

services:
    lighthouse-with-chrome:
        build:
            context: "."
            dockerfile: "Dockerfile"
        ports:
            - "8080:80"
        volumes:
            - "./:/usr/src/app"

