name: A workflow for lighthouse action
on: push
jobs:
    lighthouse_action:
      name: lighthouse action
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: run lighthouse
          uses: ./action
          with:
            TARGET_ADDRESS: "https://ratehub.ca"
        - name: save artifact
          uses: actions/upload-artifact@v1
          with:
            name: report_file
            path: /github/workspace/report.html
